### ISSUE TITLE
Force lein simpleton to serve project subdirectory outside of project context.

### ISSUE THREAD

**Issue by Gonzih** [tailrecursion/lein-simpleton#1]
Hi, I have project with directory called `deploy` in it. When I'm trying to run lein simpleton in it it always serves project directory as root. How can I force lein simpleton to ignore project directory (so I will have `deploy` directory served as a root).

**Comment by fogus** [comment]
Do you have it installed in your project.clj file or as a global Lein plugin?

**Comment by Gonzih** [comment]
It's installed as global plugin in .lein/profiles.clj.

On Wed, 2013-08-14 at 06:48 -0700, Fogus wrote:

> Do you have it installed in your project.clj file or as a global Lein
> plugin?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Regards,
Max

**Comment by fogus** [comment]
The server should serve whichever directory the command `lein simpleton <port>` was run in.  If you `cd` to the deploy directory and run that command does it not do what you want?

**Comment by fogus** [comment]
Ah wait a minute.  I see what you mean now.  It _will_ serve a non-lein directory as is, but gets confused if run in a sub-directory of a lein project.  Thanks.  I'll look at this today.

**Comment by fogus** [comment]
OK, the 1.2.0 version has a feature to specify the directory using:

```
lein simpleton <port> file :from <target-dir>
```

**Comment by Gonzih** [comment]
Thank you! You rock :)

On Tue, 2013-08-27 at 10:24 -0700, Fogus wrote:

> OK, the 1.2.0 version has a feature to specify the directory using:
> 
> lein simpleton <port> file :from <target-dir>
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Regards,
Max
